from __future__ import annotations

import logging
from datetime import datetime, timezone

from agent.llm_client import FlakeAnalysisResult
from ingestion.github_client import GitHubClient
from reporter.deduplicator import (
    FLAKE_LABEL,
    compute_signature,
    find_existing_issue,
)

logger = logging.getLogger(__name__)

CATEGORY_EMOJI = {
    "A": "🔧",
    "B": "⏱️",
    "C": "🌐",
    "D": "♻️",
}


def _format_issue_body(
    analysis: FlakeAnalysisResult,
    run_id: int | str,
    signature: str,
    occurrences: list[dict] | None = None,
) -> str:
    short_sig = signature[:12]
    emoji = CATEGORY_EMOJI.get(analysis.category, "❓")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    occ_list = occurrences or []

    occ_rows = "\n".join(
        f"| {o['date']} | [#{o['run_id']}](https://github.com/containers/podman/actions/runs/{o['run_id']}) |"
        for o in occ_list
    )
    occ_table = f"\n## 📅 Occurrence History\n\n| Date | Run |\n| :--- | :--- |\n{occ_rows}\n" if occ_rows else ""

    return f"""\
## {emoji} Flaky Test Report

| Field | Value |
| :--- | :--- |
| **Test** | `{analysis.affected_test}` |
| **Framework** | `{analysis.category_label}` |
| **Category** | **{analysis.category}** – {analysis.category_label} |
| **Confidence** | {analysis.confidence.upper()} |
| **Source** | `{analysis.affected_file}` |
| **First Seen Run** | [#{run_id}](https://github.com/containers/podman/actions/runs/{run_id}) |
| **Reported At** | {now} |

## 🔍 Root Cause

{analysis.root_cause_summary}

## 🛠️ Suggested Fix

{analysis.suggested_fix}
{occ_table}
---
> Auto-generated by the Podman Flaky Test Analyzer.  
> <!-- flake-sig:{short_sig} -->
"""


def report_failure(
    client: GitHubClient,
    analysis: FlakeAnalysisResult,
    run_id: int | str,
    test_suite: str,
    pr_number: int | None = None,
) -> dict:
    """Create a new GitHub issue or update an existing one if the flake signature matches."""
    signature = compute_signature(
        test_suite=test_suite,
        test_name=analysis.affected_test,
        error_string=analysis.root_cause_summary,
    )

    existing = find_existing_issue(client, signature)

    if existing is None:
        body = _format_issue_body(analysis, run_id, signature)
        title = (
            f"[ci/flaky] {analysis.category_label}: "
            f"{analysis.affected_test[:80]}"
        )
        issue = client.create_issue(
            title=title,
            body=body,
            labels=[FLAKE_LABEL, f"flake-category/{analysis.category}"],
        )
        logger.info("Created new flake issue #%s", issue["number"])

    else:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        comment_body = (
            f"### 🔁 Recurrence Detected ({now})\n\n"
            f"This flake was observed again in "
            f"[run #{run_id}](https://github.com/containers/podman/actions/runs/{run_id}).\n\n"
            f"**Confidence**: {analysis.confidence.upper()}\n\n"
            f"> {analysis.root_cause_summary}\n"
        )
        client.add_issue_comment(existing["number"], comment_body)
        issue = existing
        logger.info("Updated existing flake issue #%s with recurrence.", issue["number"])

    if pr_number is not None:
        pr_body = (
            f"## ⚠️ CI Failure: Known Flaky Test\n\n"
            f"The CI failure in this PR is a **known flake** unrelated to your changes.\n\n"
            f"- **Test**: `{analysis.affected_test}`\n"
            f"- **Category**: {analysis.category_label}\n"
            f"- **Tracking Issue**: #{issue['number']}\n\n"
            f"> {analysis.root_cause_summary}\n\n"
            f"You may re-run the failing jobs. "
            f"No code change from you is required."
        )
        client.create_pr_comment(pr_number, pr_body)
        logger.info("Posted flake notice on PR #%s", pr_number)

    return issue
